#!/usr/bin/env bash

: "${DOTFILES:?Must be defined}"
: "${NVIM_CONFIG:?Must be defined}"
: "${NVIM_PLUGINS:?Must be defined}"
: "${KEYBOARD_LAYOUT:?Must be defined}"

# ---- Config ------------------------------------------------------------------

mkdir -p ~/.config
mkdir -p ~/.local/share/nvim/site/pack
ln -s $NVIM_CONFIG ~/.config/nvim
ln -s $NVIM_PLUGINS ~/.local/share/nvim/site/pack/all
(cd $DOTFILES && ./symlink_create.sh)
ln -s $KEYBOARD_LAYOUT/* "$HOME/Library/Keyboard Layouts/"

# ---- Languages etc -----------------------------------------------------------

# Node, Go
brew install node
brew install go

# ---- Misc tools --------------------------------------------------------------

# git fzf curl fd z ranger nvr bat tldr 
brew install git
brew install fzf
brew install curl
brew install fd
brew install z
brew install ranger
brew install nvr
brew install bat
brew install tldr

# bash
brew install bash
sudo "echo $(which bash)" >> /etc/shells
chsh -s $(which bash)

# ---- Neovim ------------------------------------------------------------------

# Neovim
brew install neovim

# LSP servers
npm install -g typescript-language-server typescript
npm install -g prettier
brew install gopls

# Providers: Python, Node, Ruby
pip3 install pynvim
npm install -g neovim
sudo gem install neovim

# Treesitter (vim, lua, c are bundled with Neovim)
nvim --headless -c "TSInstallSync! javascript typescript go" -c "quit"
